// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookOrder.proto

public final class BookOrder {
  private BookOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BookOrderRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use BookOrderRequest.newBuilder() to construct.
    private BookOrderRequest() {
      initFields();
    }
    private BookOrderRequest(boolean noInit) {}
    
    private static final BookOrderRequest defaultInstance;
    public static BookOrderRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public BookOrderRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookOrder.internal_static_BookOrderRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookOrder.internal_static_BookOrderRequest_fieldAccessorTable;
    }
    
    // required .Customer customer = 1;
    public static final int CUSTOMER_FIELD_NUMBER = 1;
    private boolean hasCustomer;
    private BookOrder.Customer customer_;
    public boolean hasCustomer() { return hasCustomer; }
    public BookOrder.Customer getCustomer() { return customer_; }
    
    // required .Book book = 2;
    public static final int BOOK_FIELD_NUMBER = 2;
    private boolean hasBook;
    private BookOrder.Book book_;
    public boolean hasBook() { return hasBook; }
    public BookOrder.Book getBook() { return book_; }
    
    // required bool deliverToCustomer = 3;
    public static final int DELIVERTOCUSTOMER_FIELD_NUMBER = 3;
    private boolean hasDeliverToCustomer;
    private boolean deliverToCustomer_ = false;
    public boolean hasDeliverToCustomer() { return hasDeliverToCustomer; }
    public boolean getDeliverToCustomer() { return deliverToCustomer_; }
    
    private void initFields() {
      customer_ = BookOrder.Customer.getDefaultInstance();
      book_ = BookOrder.Book.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasCustomer) return false;
      if (!hasBook) return false;
      if (!hasDeliverToCustomer) return false;
      if (!getCustomer().isInitialized()) return false;
      if (!getBook().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCustomer()) {
        output.writeMessage(1, getCustomer());
      }
      if (hasBook()) {
        output.writeMessage(2, getBook());
      }
      if (hasDeliverToCustomer()) {
        output.writeBool(3, getDeliverToCustomer());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCustomer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCustomer());
      }
      if (hasBook()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBook());
      }
      if (hasDeliverToCustomer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getDeliverToCustomer());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static BookOrder.BookOrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.BookOrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.BookOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.BookOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BookOrder.BookOrderRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private BookOrder.BookOrderRequest result;
      
      // Construct using BookOrder.BookOrderRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new BookOrder.BookOrderRequest();
        return builder;
      }
      
      protected BookOrder.BookOrderRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new BookOrder.BookOrderRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BookOrder.BookOrderRequest.getDescriptor();
      }
      
      public BookOrder.BookOrderRequest getDefaultInstanceForType() {
        return BookOrder.BookOrderRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public BookOrder.BookOrderRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private BookOrder.BookOrderRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public BookOrder.BookOrderRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        BookOrder.BookOrderRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BookOrder.BookOrderRequest) {
          return mergeFrom((BookOrder.BookOrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BookOrder.BookOrderRequest other) {
        if (other == BookOrder.BookOrderRequest.getDefaultInstance()) return this;
        if (other.hasCustomer()) {
          mergeCustomer(other.getCustomer());
        }
        if (other.hasBook()) {
          mergeBook(other.getBook());
        }
        if (other.hasDeliverToCustomer()) {
          setDeliverToCustomer(other.getDeliverToCustomer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              BookOrder.Customer.Builder subBuilder = BookOrder.Customer.newBuilder();
              if (hasCustomer()) {
                subBuilder.mergeFrom(getCustomer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCustomer(subBuilder.buildPartial());
              break;
            }
            case 18: {
              BookOrder.Book.Builder subBuilder = BookOrder.Book.newBuilder();
              if (hasBook()) {
                subBuilder.mergeFrom(getBook());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBook(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setDeliverToCustomer(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required .Customer customer = 1;
      public boolean hasCustomer() {
        return result.hasCustomer();
      }
      public BookOrder.Customer getCustomer() {
        return result.getCustomer();
      }
      public Builder setCustomer(BookOrder.Customer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCustomer = true;
        result.customer_ = value;
        return this;
      }
      public Builder setCustomer(BookOrder.Customer.Builder builderForValue) {
        result.hasCustomer = true;
        result.customer_ = builderForValue.build();
        return this;
      }
      public Builder mergeCustomer(BookOrder.Customer value) {
        if (result.hasCustomer() &&
            result.customer_ != BookOrder.Customer.getDefaultInstance()) {
          result.customer_ =
            BookOrder.Customer.newBuilder(result.customer_).mergeFrom(value).buildPartial();
        } else {
          result.customer_ = value;
        }
        result.hasCustomer = true;
        return this;
      }
      public Builder clearCustomer() {
        result.hasCustomer = false;
        result.customer_ = BookOrder.Customer.getDefaultInstance();
        return this;
      }
      
      // required .Book book = 2;
      public boolean hasBook() {
        return result.hasBook();
      }
      public BookOrder.Book getBook() {
        return result.getBook();
      }
      public Builder setBook(BookOrder.Book value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBook = true;
        result.book_ = value;
        return this;
      }
      public Builder setBook(BookOrder.Book.Builder builderForValue) {
        result.hasBook = true;
        result.book_ = builderForValue.build();
        return this;
      }
      public Builder mergeBook(BookOrder.Book value) {
        if (result.hasBook() &&
            result.book_ != BookOrder.Book.getDefaultInstance()) {
          result.book_ =
            BookOrder.Book.newBuilder(result.book_).mergeFrom(value).buildPartial();
        } else {
          result.book_ = value;
        }
        result.hasBook = true;
        return this;
      }
      public Builder clearBook() {
        result.hasBook = false;
        result.book_ = BookOrder.Book.getDefaultInstance();
        return this;
      }
      
      // required bool deliverToCustomer = 3;
      public boolean hasDeliverToCustomer() {
        return result.hasDeliverToCustomer();
      }
      public boolean getDeliverToCustomer() {
        return result.getDeliverToCustomer();
      }
      public Builder setDeliverToCustomer(boolean value) {
        result.hasDeliverToCustomer = true;
        result.deliverToCustomer_ = value;
        return this;
      }
      public Builder clearDeliverToCustomer() {
        result.hasDeliverToCustomer = false;
        result.deliverToCustomer_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BookOrderRequest)
    }
    
    static {
      defaultInstance = new BookOrderRequest(true);
      BookOrder.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BookOrderRequest)
  }
  
  public static final class BookOrderResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use BookOrderResponse.newBuilder() to construct.
    private BookOrderResponse() {
      initFields();
    }
    private BookOrderResponse(boolean noInit) {}
    
    private static final BookOrderResponse defaultInstance;
    public static BookOrderResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BookOrderResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookOrder.internal_static_BookOrderResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookOrder.internal_static_BookOrderResponse_fieldAccessorTable;
    }
    
    // required uint64 orderNumber = 1;
    public static final int ORDERNUMBER_FIELD_NUMBER = 1;
    private boolean hasOrderNumber;
    private long orderNumber_ = 0L;
    public boolean hasOrderNumber() { return hasOrderNumber; }
    public long getOrderNumber() { return orderNumber_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasOrderNumber) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOrderNumber()) {
        output.writeUInt64(1, getOrderNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOrderNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getOrderNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static BookOrder.BookOrderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.BookOrderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.BookOrderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.BookOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.BookOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BookOrder.BookOrderResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private BookOrder.BookOrderResponse result;
      
      // Construct using BookOrder.BookOrderResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new BookOrder.BookOrderResponse();
        return builder;
      }
      
      protected BookOrder.BookOrderResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new BookOrder.BookOrderResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BookOrder.BookOrderResponse.getDescriptor();
      }
      
      public BookOrder.BookOrderResponse getDefaultInstanceForType() {
        return BookOrder.BookOrderResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public BookOrder.BookOrderResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private BookOrder.BookOrderResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public BookOrder.BookOrderResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        BookOrder.BookOrderResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BookOrder.BookOrderResponse) {
          return mergeFrom((BookOrder.BookOrderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BookOrder.BookOrderResponse other) {
        if (other == BookOrder.BookOrderResponse.getDefaultInstance()) return this;
        if (other.hasOrderNumber()) {
          setOrderNumber(other.getOrderNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setOrderNumber(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 orderNumber = 1;
      public boolean hasOrderNumber() {
        return result.hasOrderNumber();
      }
      public long getOrderNumber() {
        return result.getOrderNumber();
      }
      public Builder setOrderNumber(long value) {
        result.hasOrderNumber = true;
        result.orderNumber_ = value;
        return this;
      }
      public Builder clearOrderNumber() {
        result.hasOrderNumber = false;
        result.orderNumber_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BookOrderResponse)
    }
    
    static {
      defaultInstance = new BookOrderResponse(true);
      BookOrder.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BookOrderResponse)
  }
  
  public static final class Customer extends
      com.google.protobuf.GeneratedMessage {
    // Use Customer.newBuilder() to construct.
    private Customer() {
      initFields();
    }
    private Customer(boolean noInit) {}
    
    private static final Customer defaultInstance;
    public static Customer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Customer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookOrder.internal_static_Customer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookOrder.internal_static_Customer_fieldAccessorTable;
    }
    
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      UNKNOWN(0, 0),
      MALE(1, 1),
      FEMALE(2, 2),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Gender valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return MALE;
          case 2: return FEMALE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BookOrder.Customer.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Gender[] VALUES = {
        UNKNOWN, MALE, FEMALE, 
      };
      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Gender(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        BookOrder.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:Customer.Gender)
    }
    
    // required uint32 customerNumber = 1;
    public static final int CUSTOMERNUMBER_FIELD_NUMBER = 1;
    private boolean hasCustomerNumber;
    private int customerNumber_ = 0;
    public boolean hasCustomerNumber() { return hasCustomerNumber; }
    public int getCustomerNumber() { return customerNumber_; }
    
    // required .Customer.Gender gender = 2 [default = UNKNOWN];
    public static final int GENDER_FIELD_NUMBER = 2;
    private boolean hasGender;
    private BookOrder.Customer.Gender gender_;
    public boolean hasGender() { return hasGender; }
    public BookOrder.Customer.Gender getGender() { return gender_; }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required string address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // optional uint32 phone = 5;
    public static final int PHONE_FIELD_NUMBER = 5;
    private boolean hasPhone;
    private int phone_ = 0;
    public boolean hasPhone() { return hasPhone; }
    public int getPhone() { return phone_; }
    
    private void initFields() {
      gender_ = BookOrder.Customer.Gender.UNKNOWN;
    }
    public final boolean isInitialized() {
      if (!hasCustomerNumber) return false;
      if (!hasGender) return false;
      if (!hasName) return false;
      if (!hasAddress) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCustomerNumber()) {
        output.writeUInt32(1, getCustomerNumber());
      }
      if (hasGender()) {
        output.writeEnum(2, getGender().getNumber());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasAddress()) {
        output.writeString(4, getAddress());
      }
      if (hasPhone()) {
        output.writeUInt32(5, getPhone());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCustomerNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getCustomerNumber());
      }
      if (hasGender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getGender().getNumber());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getAddress());
      }
      if (hasPhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, getPhone());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static BookOrder.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BookOrder.Customer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private BookOrder.Customer result;
      
      // Construct using BookOrder.Customer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new BookOrder.Customer();
        return builder;
      }
      
      protected BookOrder.Customer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new BookOrder.Customer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BookOrder.Customer.getDescriptor();
      }
      
      public BookOrder.Customer getDefaultInstanceForType() {
        return BookOrder.Customer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public BookOrder.Customer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private BookOrder.Customer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public BookOrder.Customer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        BookOrder.Customer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BookOrder.Customer) {
          return mergeFrom((BookOrder.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BookOrder.Customer other) {
        if (other == BookOrder.Customer.getDefaultInstance()) return this;
        if (other.hasCustomerNumber()) {
          setCustomerNumber(other.getCustomerNumber());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCustomerNumber(input.readUInt32());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              BookOrder.Customer.Gender value = BookOrder.Customer.Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setGender(value);
              }
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 34: {
              setAddress(input.readString());
              break;
            }
            case 40: {
              setPhone(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required uint32 customerNumber = 1;
      public boolean hasCustomerNumber() {
        return result.hasCustomerNumber();
      }
      public int getCustomerNumber() {
        return result.getCustomerNumber();
      }
      public Builder setCustomerNumber(int value) {
        result.hasCustomerNumber = true;
        result.customerNumber_ = value;
        return this;
      }
      public Builder clearCustomerNumber() {
        result.hasCustomerNumber = false;
        result.customerNumber_ = 0;
        return this;
      }
      
      // required .Customer.Gender gender = 2 [default = UNKNOWN];
      public boolean hasGender() {
        return result.hasGender();
      }
      public BookOrder.Customer.Gender getGender() {
        return result.getGender();
      }
      public Builder setGender(BookOrder.Customer.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGender = true;
        result.gender_ = value;
        return this;
      }
      public Builder clearGender() {
        result.hasGender = false;
        result.gender_ = BookOrder.Customer.Gender.UNKNOWN;
        return this;
      }
      
      // required string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required string address = 4;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // optional uint32 phone = 5;
      public boolean hasPhone() {
        return result.hasPhone();
      }
      public int getPhone() {
        return result.getPhone();
      }
      public Builder setPhone(int value) {
        result.hasPhone = true;
        result.phone_ = value;
        return this;
      }
      public Builder clearPhone() {
        result.hasPhone = false;
        result.phone_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Customer)
    }
    
    static {
      defaultInstance = new Customer(true);
      BookOrder.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Customer)
  }
  
  public static final class Book extends
      com.google.protobuf.GeneratedMessage {
    // Use Book.newBuilder() to construct.
    private Book() {
      initFields();
    }
    private Book(boolean noInit) {}
    
    private static final Book defaultInstance;
    public static Book getDefaultInstance() {
      return defaultInstance;
    }
    
    public Book getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookOrder.internal_static_Book_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookOrder.internal_static_Book_fieldAccessorTable;
    }
    
    // required string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // repeated string authors = 2;
    public static final int AUTHORS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> authors_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getAuthorsList() {
      return authors_;
    }
    public int getAuthorsCount() { return authors_.size(); }
    public java.lang.String getAuthors(int index) {
      return authors_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTitle) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTitle()) {
        output.writeString(1, getTitle());
      }
      for (java.lang.String element : getAuthorsList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTitle());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getAuthorsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getAuthorsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static BookOrder.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BookOrder.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BookOrder.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BookOrder.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BookOrder.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BookOrder.Book prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private BookOrder.Book result;
      
      // Construct using BookOrder.Book.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new BookOrder.Book();
        return builder;
      }
      
      protected BookOrder.Book internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new BookOrder.Book();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BookOrder.Book.getDescriptor();
      }
      
      public BookOrder.Book getDefaultInstanceForType() {
        return BookOrder.Book.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public BookOrder.Book build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private BookOrder.Book buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public BookOrder.Book buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.authors_ != java.util.Collections.EMPTY_LIST) {
          result.authors_ =
            java.util.Collections.unmodifiableList(result.authors_);
        }
        BookOrder.Book returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BookOrder.Book) {
          return mergeFrom((BookOrder.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BookOrder.Book other) {
        if (other == BookOrder.Book.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (!other.authors_.isEmpty()) {
          if (result.authors_.isEmpty()) {
            result.authors_ = new java.util.ArrayList<java.lang.String>();
          }
          result.authors_.addAll(other.authors_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTitle(input.readString());
              break;
            }
            case 18: {
              addAuthors(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string title = 1;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // repeated string authors = 2;
      public java.util.List<java.lang.String> getAuthorsList() {
        return java.util.Collections.unmodifiableList(result.authors_);
      }
      public int getAuthorsCount() {
        return result.getAuthorsCount();
      }
      public java.lang.String getAuthors(int index) {
        return result.getAuthors(index);
      }
      public Builder setAuthors(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.authors_.set(index, value);
        return this;
      }
      public Builder addAuthors(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.authors_.isEmpty()) {
          result.authors_ = new java.util.ArrayList<java.lang.String>();
        }
        result.authors_.add(value);
        return this;
      }
      public Builder addAllAuthors(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.authors_.isEmpty()) {
          result.authors_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.authors_);
        return this;
      }
      public Builder clearAuthors() {
        result.authors_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Book)
    }
    
    static {
      defaultInstance = new Book(true);
      BookOrder.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Book)
  }
  
  public static abstract class BookOrderService
      implements com.google.protobuf.Service {
    protected BookOrderService() {}
    
    public interface Interface {
      public abstract void order(
          com.google.protobuf.RpcController controller,
          BookOrder.BookOrderRequest request,
          com.google.protobuf.RpcCallback<BookOrder.BookOrderResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BookOrderService() {
        @Override
        public  void order(
            com.google.protobuf.RpcController controller,
            BookOrder.BookOrderRequest request,
            com.google.protobuf.RpcCallback<BookOrder.BookOrderResponse> done) {
          impl.order(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.order(controller, (BookOrder.BookOrderRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return BookOrder.BookOrderRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return BookOrder.BookOrderResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void order(
        com.google.protobuf.RpcController controller,
        BookOrder.BookOrderRequest request,
        com.google.protobuf.RpcCallback<BookOrder.BookOrderResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return BookOrder.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.order(controller, (BookOrder.BookOrderRequest)request,
            com.google.protobuf.RpcUtil.<BookOrder.BookOrderResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return BookOrder.BookOrderRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return BookOrder.BookOrderResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends BookOrder.BookOrderService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void order(
          com.google.protobuf.RpcController controller,
          BookOrder.BookOrderRequest request,
          com.google.protobuf.RpcCallback<BookOrder.BookOrderResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          BookOrder.BookOrderResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            BookOrder.BookOrderResponse.class,
            BookOrder.BookOrderResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public BookOrder.BookOrderResponse order(
          com.google.protobuf.RpcController controller,
          BookOrder.BookOrderRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public BookOrder.BookOrderResponse order(
          com.google.protobuf.RpcController controller,
          BookOrder.BookOrderRequest request)
          throws com.google.protobuf.ServiceException {
        return (BookOrder.BookOrderResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          BookOrder.BookOrderResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BookOrderRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BookOrderRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BookOrderResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BookOrderResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Customer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Customer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017bookOrder.proto\"_\n\020BookOrderRequest\022\033\n" +
      "\010customer\030\001 \002(\0132\t.Customer\022\023\n\004book\030\002 \002(\013" +
      "2\005.Book\022\031\n\021deliverToCustomer\030\003 \002(\010\"(\n\021Bo" +
      "okOrderResponse\022\023\n\013orderNumber\030\001 \002(\004\"\250\001\n" +
      "\010Customer\022\026\n\016customerNumber\030\001 \002(\r\022)\n\006gen" +
      "der\030\002 \002(\0162\020.Customer.Gender:\007UNKNOWN\022\014\n\004" +
      "name\030\003 \002(\t\022\017\n\007address\030\004 \002(\t\022\r\n\005phone\030\005 \001" +
      "(\r\"+\n\006Gender\022\013\n\007UNKNOWN\020\000\022\010\n\004MALE\020\001\022\n\n\006F" +
      "EMALE\020\002\"&\n\004Book\022\r\n\005title\030\001 \002(\t\022\017\n\007author" +
      "s\030\002 \003(\t2B\n\020BookOrderService\022.\n\005order\022\021.B",
      "ookOrderRequest\032\022.BookOrderResponseB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BookOrderRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BookOrderRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BookOrderRequest_descriptor,
              new java.lang.String[] { "Customer", "Book", "DeliverToCustomer", },
              BookOrder.BookOrderRequest.class,
              BookOrder.BookOrderRequest.Builder.class);
          internal_static_BookOrderResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BookOrderResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BookOrderResponse_descriptor,
              new java.lang.String[] { "OrderNumber", },
              BookOrder.BookOrderResponse.class,
              BookOrder.BookOrderResponse.Builder.class);
          internal_static_Customer_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Customer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Customer_descriptor,
              new java.lang.String[] { "CustomerNumber", "Gender", "Name", "Address", "Phone", },
              BookOrder.Customer.class,
              BookOrder.Customer.Builder.class);
          internal_static_Book_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Book_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Book_descriptor,
              new java.lang.String[] { "Title", "Authors", },
              BookOrder.Book.class,
              BookOrder.Book.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
