// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/FlashNodeServiceProtocol.proto

package de.uniluebeck.itm.example.rpc.flashnodeservice.protocol;

import com.google.protobuf.Message;

public final class FlashNodeServiceProtocol {
  private FlashNodeServiceProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FlashNodeRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use FlashNodeRequest.newBuilder() to construct.
    private FlashNodeRequest() {
      initFields();
    }
    private FlashNodeRequest(boolean noInit) {}
    
    private static final FlashNodeRequest defaultInstance;
    public static FlashNodeRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FlashNodeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_fieldAccessorTable;
    }
    
    // required uint32 delay = 1;
    public static final int DELAY_FIELD_NUMBER = 1;
    private boolean hasDelay;
    private int delay_ = 0;
    public boolean hasDelay() { return hasDelay; }
    public int getDelay() { return delay_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDelay) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDelay()) {
        output.writeUInt32(1, getDelay());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDelay()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getDelay());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest result;
      
      // Construct using de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest();
        return builder;
      }
      
      protected de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest) {
          return mergeFrom((de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest other) {
        if (other == de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.getDefaultInstance()) return this;
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setDelay(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required uint32 delay = 1;
      public boolean hasDelay() {
        return result.hasDelay();
      }
      public int getDelay() {
        return result.getDelay();
      }
      public Builder setDelay(int value) {
        result.hasDelay = true;
        result.delay_ = value;
        return this;
      }
      public Builder clearDelay() {
        result.hasDelay = false;
        result.delay_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeRequest)
    }
    
    static {
      defaultInstance = new FlashNodeRequest(true);
      de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeRequest)
  }
  
  public static final class FlashNodeResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use FlashNodeResponse.newBuilder() to construct.
    private FlashNodeResponse() {
      initFields();
    }
    private FlashNodeResponse(boolean noInit) {}
    
    private static final FlashNodeResponse defaultInstance;
    public static FlashNodeResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public FlashNodeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_fieldAccessorTable;
    }
    
    // required bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean hasSuccess;
    private boolean success_ = false;
    public boolean hasSuccess() { return hasSuccess; }
    public boolean getSuccess() { return success_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSuccess) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSuccess()) {
        output.writeBool(1, getSuccess());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSuccess()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getSuccess());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse result;
      
      // Construct using de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse();
        return builder;
      }
      
      protected de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse) {
          return mergeFrom((de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse other) {
        if (other == de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSuccess(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required bool success = 1;
      public boolean hasSuccess() {
        return result.hasSuccess();
      }
      public boolean getSuccess() {
        return result.getSuccess();
      }
      public Builder setSuccess(boolean value) {
        result.hasSuccess = true;
        result.success_ = value;
        return this;
      }
      public Builder clearSuccess() {
        result.hasSuccess = false;
        result.success_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeResponse)
    }
    
    static {
      defaultInstance = new FlashNodeResponse(true);
      de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeResponse)
  }
  
  public static abstract class FlashNodeService
      implements com.google.protobuf.Service {
    protected FlashNodeService() {}
    
    public interface Interface {
      public abstract void flashNode(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request,
          com.google.protobuf.RpcCallback<de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new FlashNodeService() {
        @Override
        public  void flashNode(
            com.google.protobuf.RpcController controller,
            de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request,
            com.google.protobuf.RpcCallback<de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse> done) {
          impl.flashNode(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.flashNode(controller, (de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void flashNode(
        com.google.protobuf.RpcController controller,
        de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request,
        com.google.protobuf.RpcCallback<de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.flashNode(controller, (de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest)request,
            com.google.protobuf.RpcUtil.<de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void flashNode(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request,
          com.google.protobuf.RpcCallback<de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.class,
            de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse flashNode(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse flashNode(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest request)
          throws com.google.protobuf.ServiceException {
        return (de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/main/resources/FlashNodeServicePro" +
      "tocol.proto\0227de.uniluebeck.itm.example.r" +
      "pc.flashnodeservice.protocol\"!\n\020FlashNod" +
      "eRequest\022\r\n\005delay\030\001 \002(\r\"$\n\021FlashNodeResp" +
      "onse\022\017\n\007success\030\001 \002(\0102\267\001\n\020FlashNodeServi" +
      "ce\022\242\001\n\tflashNode\022I.de.uniluebeck.itm.exa" +
      "mple.rpc.flashnodeservice.protocol.Flash" +
      "NodeRequest\032J.de.uniluebeck.itm.example." +
      "rpc.flashnodeservice.protocol.FlashNodeR" +
      "esponseB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeRequest_descriptor,
              new java.lang.String[] { "Delay", },
              de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.class,
              de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeRequest.Builder.class);
          internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_example_rpc_flashnodeservice_protocol_FlashNodeResponse_descriptor,
              new java.lang.String[] { "Success", },
              de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.class,
              de.uniluebeck.itm.example.rpc.flashnodeservice.protocol.FlashNodeServiceProtocol.FlashNodeResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
