// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/MittagsServiceProtocol.proto

package de.uniluebeck.itm.rpc.mittagsservice.protocol;

import com.google.protobuf.Message;

public final class MittagsServiceProtocol {
  private MittagsServiceProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BestellRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use BestellRequest.newBuilder() to construct.
    private BestellRequest() {
      initFields();
    }
    private BestellRequest(boolean noInit) {}
    
    private static final BestellRequest defaultInstance;
    public static BestellRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public BestellRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_fieldAccessorTable;
    }
    
    // required .de.uniluebeck.itm.rpc.mittagsservice.protocol.Gericht gericht = 1;
    public static final int GERICHT_FIELD_NUMBER = 1;
    private boolean hasGericht;
    private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht gericht_;
    public boolean hasGericht() { return hasGericht; }
    public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht getGericht() { return gericht_; }
    
    // required uint32 anzahl = 2;
    public static final int ANZAHL_FIELD_NUMBER = 2;
    private boolean hasAnzahl;
    private int anzahl_ = 0;
    public boolean hasAnzahl() { return hasAnzahl; }
    public int getAnzahl() { return anzahl_; }
    
    private void initFields() {
      gericht_ = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasGericht) return false;
      if (!hasAnzahl) return false;
      if (!getGericht().isInitialized()) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGericht()) {
        output.writeMessage(1, getGericht());
      }
      if (hasAnzahl()) {
        output.writeUInt32(2, getAnzahl());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGericht()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGericht());
      }
      if (hasAnzahl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getAnzahl());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest result;
      
      // Construct using de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest();
        return builder;
      }
      
      protected de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest) {
          return mergeFrom((de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest other) {
        if (other == de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.getDefaultInstance()) return this;
        if (other.hasGericht()) {
          mergeGericht(other.getGericht());
        }
        if (other.hasAnzahl()) {
          setAnzahl(other.getAnzahl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.Builder subBuilder = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.newBuilder();
              if (hasGericht()) {
                subBuilder.mergeFrom(getGericht());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGericht(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setAnzahl(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required .de.uniluebeck.itm.rpc.mittagsservice.protocol.Gericht gericht = 1;
      public boolean hasGericht() {
        return result.hasGericht();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht getGericht() {
        return result.getGericht();
      }
      public Builder setGericht(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGericht = true;
        result.gericht_ = value;
        return this;
      }
      public Builder setGericht(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.Builder builderForValue) {
        result.hasGericht = true;
        result.gericht_ = builderForValue.build();
        return this;
      }
      public Builder mergeGericht(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht value) {
        if (result.hasGericht() &&
            result.gericht_ != de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDefaultInstance()) {
          result.gericht_ =
            de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.newBuilder(result.gericht_).mergeFrom(value).buildPartial();
        } else {
          result.gericht_ = value;
        }
        result.hasGericht = true;
        return this;
      }
      public Builder clearGericht() {
        result.hasGericht = false;
        result.gericht_ = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDefaultInstance();
        return this;
      }
      
      // required uint32 anzahl = 2;
      public boolean hasAnzahl() {
        return result.hasAnzahl();
      }
      public int getAnzahl() {
        return result.getAnzahl();
      }
      public Builder setAnzahl(int value) {
        result.hasAnzahl = true;
        result.anzahl_ = value;
        return this;
      }
      public Builder clearAnzahl() {
        result.hasAnzahl = false;
        result.anzahl_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.BestellRequest)
    }
    
    static {
      defaultInstance = new BestellRequest(true);
      de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.BestellRequest)
  }
  
  public static final class BestellResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use BestellResponse.newBuilder() to construct.
    private BestellResponse() {
      initFields();
    }
    private BestellResponse(boolean noInit) {}
    
    private static final BestellResponse defaultInstance;
    public static BestellResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BestellResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_fieldAccessorTable;
    }
    
    // required .de.uniluebeck.itm.rpc.mittagsservice.protocol.Mahlzeit mahlzeit = 1;
    public static final int MAHLZEIT_FIELD_NUMBER = 1;
    private boolean hasMahlzeit;
    private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit mahlzeit_;
    public boolean hasMahlzeit() { return hasMahlzeit; }
    public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit getMahlzeit() { return mahlzeit_; }
    
    private void initFields() {
      mahlzeit_ = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasMahlzeit) return false;
      if (!getMahlzeit().isInitialized()) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMahlzeit()) {
        output.writeMessage(1, getMahlzeit());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMahlzeit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMahlzeit());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse result;
      
      // Construct using de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse();
        return builder;
      }
      
      protected de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse) {
          return mergeFrom((de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse other) {
        if (other == de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance()) return this;
        if (other.hasMahlzeit()) {
          mergeMahlzeit(other.getMahlzeit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.Builder subBuilder = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.newBuilder();
              if (hasMahlzeit()) {
                subBuilder.mergeFrom(getMahlzeit());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMahlzeit(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .de.uniluebeck.itm.rpc.mittagsservice.protocol.Mahlzeit mahlzeit = 1;
      public boolean hasMahlzeit() {
        return result.hasMahlzeit();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit getMahlzeit() {
        return result.getMahlzeit();
      }
      public Builder setMahlzeit(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMahlzeit = true;
        result.mahlzeit_ = value;
        return this;
      }
      public Builder setMahlzeit(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.Builder builderForValue) {
        result.hasMahlzeit = true;
        result.mahlzeit_ = builderForValue.build();
        return this;
      }
      public Builder mergeMahlzeit(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit value) {
        if (result.hasMahlzeit() &&
            result.mahlzeit_ != de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDefaultInstance()) {
          result.mahlzeit_ =
            de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.newBuilder(result.mahlzeit_).mergeFrom(value).buildPartial();
        } else {
          result.mahlzeit_ = value;
        }
        result.hasMahlzeit = true;
        return this;
      }
      public Builder clearMahlzeit() {
        result.hasMahlzeit = false;
        result.mahlzeit_ = de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.BestellResponse)
    }
    
    static {
      defaultInstance = new BestellResponse(true);
      de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.BestellResponse)
  }
  
  public static final class Gericht extends
      com.google.protobuf.GeneratedMessage {
    // Use Gericht.newBuilder() to construct.
    private Gericht() {
      initFields();
    }
    private Gericht(boolean noInit) {}
    
    private static final Gericht defaultInstance;
    public static Gericht getDefaultInstance() {
      return defaultInstance;
    }
    
    public Gericht getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht result;
      
      // Construct using de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht();
        return builder;
      }
      
      protected de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDescriptor();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht getDefaultInstanceForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht) {
          return mergeFrom((de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht other) {
        if (other == de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.Gericht)
    }
    
    static {
      defaultInstance = new Gericht(true);
      de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.Gericht)
  }
  
  public static final class Mahlzeit extends
      com.google.protobuf.GeneratedMessage {
    // Use Mahlzeit.newBuilder() to construct.
    private Mahlzeit() {
      initFields();
    }
    private Mahlzeit(boolean noInit) {}
    
    private static final Mahlzeit defaultInstance;
    public static Mahlzeit getDefaultInstance() {
      return defaultInstance;
    }
    
    public Mahlzeit getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit result;
      
      // Construct using de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit();
        return builder;
      }
      
      protected de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDescriptor();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit getDefaultInstanceForType() {
        return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit) {
          return mergeFrom((de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit other) {
        if (other == de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.Mahlzeit)
    }
    
    static {
      defaultInstance = new Mahlzeit(true);
      de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.rpc.mittagsservice.protocol.Mahlzeit)
  }
  
  public static abstract class MittagsService
      implements com.google.protobuf.Service {
    protected MittagsService() {}
    
    public interface Interface {
      public abstract void bestelle(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request,
          com.google.protobuf.RpcCallback<de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MittagsService() {
        @Override
        public  void bestelle(
            com.google.protobuf.RpcController controller,
            de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request,
            com.google.protobuf.RpcCallback<de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse> done) {
          impl.bestelle(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.bestelle(controller, (de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void bestelle(
        com.google.protobuf.RpcController controller,
        de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request,
        com.google.protobuf.RpcCallback<de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.bestelle(controller, (de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest)request,
            com.google.protobuf.RpcUtil.<de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.MittagsService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void bestelle(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request,
          com.google.protobuf.RpcCallback<de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.class,
            de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse bestelle(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse bestelle(
          com.google.protobuf.RpcController controller,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest request)
          throws com.google.protobuf.ServiceException {
        return (de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/resources/MittagsServiceProto" +
      "col.proto\022-de.uniluebeck.itm.rpc.mittags" +
      "service.protocol\"i\n\016BestellRequest\022G\n\007ge" +
      "richt\030\001 \002(\01326.de.uniluebeck.itm.rpc.mitt" +
      "agsservice.protocol.Gericht\022\016\n\006anzahl\030\002 " +
      "\002(\r\"\\\n\017BestellResponse\022I\n\010mahlzeit\030\001 \002(\013" +
      "27.de.uniluebeck.itm.rpc.mittagsservice." +
      "protocol.Mahlzeit\"\027\n\007Gericht\022\014\n\004name\030\001 \002" +
      "(\t\"\030\n\010Mahlzeit\022\014\n\004name\030\001 \002(\t2\234\001\n\016Mittags" +
      "Service\022\211\001\n\010bestelle\022=.de.uniluebeck.itm",
      ".rpc.mittagsservice.protocol.BestellRequ" +
      "est\032>.de.uniluebeck.itm.rpc.mittagsservi" +
      "ce.protocol.BestellResponseB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellRequest_descriptor,
              new java.lang.String[] { "Gericht", "Anzahl", },
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.class,
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellRequest.Builder.class);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_BestellResponse_descriptor,
              new java.lang.String[] { "Mahlzeit", },
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.class,
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.BestellResponse.Builder.class);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Gericht_descriptor,
              new java.lang.String[] { "Name", },
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.class,
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Gericht.Builder.class);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_rpc_mittagsservice_protocol_Mahlzeit_descriptor,
              new java.lang.String[] { "Name", },
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.class,
              de.uniluebeck.itm.rpc.mittagsservice.protocol.MittagsServiceProtocol.Mahlzeit.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
