// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/mep.proto

package de.uniluebeck.itm.ubermep.mep.protocol;

import com.google.protobuf.Message;

public final class MEP {
  private MEP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    UNICAST(0, 1),
    MULTICAST(1, 2),
    SINGLE_RESPONSE_REQUEST(2, 3),
    MULTI_RESPONSE_REQUEST(3, 4),
    SINGLE_RESPONSE(4, 5),
    MULTI_RESPONSE(5, 6),
    RPC_REQUEST(6, 7),
    RPC_RESPONSE(7, 8),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return UNICAST;
        case 2: return MULTICAST;
        case 3: return SINGLE_RESPONSE_REQUEST;
        case 4: return MULTI_RESPONSE_REQUEST;
        case 5: return SINGLE_RESPONSE;
        case 6: return MULTI_RESPONSE;
        case 7: return RPC_REQUEST;
        case 8: return RPC_RESPONSE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      UNICAST, MULTICAST, SINGLE_RESPONSE_REQUEST, MULTI_RESPONSE_REQUEST, SINGLE_RESPONSE, MULTI_RESPONSE, RPC_REQUEST, RPC_RESPONSE, 
    };
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      de.uniluebeck.itm.ubermep.mep.protocol.MEP.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:de.uniluebeck.itm.ubermep.mep.protocol.MessageType)
  }
  
  public enum ServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    SERVICE(0, 1),
    BLOCKING_SERVICE(1, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static ServiceType valueOf(int value) {
      switch (value) {
        case 1: return SERVICE;
        case 2: return BLOCKING_SERVICE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceType>() {
            public ServiceType findValueByNumber(int number) {
              return ServiceType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final ServiceType[] VALUES = {
      SERVICE, BLOCKING_SERVICE, 
    };
    public static ServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private ServiceType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      de.uniluebeck.itm.ubermep.mep.protocol.MEP.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:de.uniluebeck.itm.ubermep.mep.protocol.ServiceType)
  }
  
  public static final class MEPPacket extends
      com.google.protobuf.GeneratedMessage {
    // Use MEPPacket.newBuilder() to construct.
    private MEPPacket() {
      initFields();
    }
    private MEPPacket(boolean noInit) {}
    
    private static final MEPPacket defaultInstance;
    public static MEPPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public MEPPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_fieldAccessorTable;
    }
    
    // required bool reliable = 1;
    public static final int RELIABLE_FIELD_NUMBER = 1;
    private boolean hasReliable;
    private boolean reliable_ = false;
    public boolean hasReliable() { return hasReliable; }
    public boolean getReliable() { return reliable_; }
    
    // required .de.uniluebeck.itm.ubermep.mep.protocol.MessageType messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private boolean hasMessageType;
    private de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType messageType_;
    public boolean hasMessageType() { return hasMessageType; }
    public de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType getMessageType() { return messageType_; }
    
    // required bytes payload = 3;
    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    // optional uint32 requestID = 4;
    public static final int REQUESTID_FIELD_NUMBER = 4;
    private boolean hasRequestID;
    private int requestID_ = 0;
    public boolean hasRequestID() { return hasRequestID; }
    public int getRequestID() { return requestID_; }
    
    // optional bool exceptionOccurred = 5;
    public static final int EXCEPTIONOCCURRED_FIELD_NUMBER = 5;
    private boolean hasExceptionOccurred;
    private boolean exceptionOccurred_ = false;
    public boolean hasExceptionOccurred() { return hasExceptionOccurred; }
    public boolean getExceptionOccurred() { return exceptionOccurred_; }
    
    // optional uint32 currentMessageNumber = 6;
    public static final int CURRENTMESSAGENUMBER_FIELD_NUMBER = 6;
    private boolean hasCurrentMessageNumber;
    private int currentMessageNumber_ = 0;
    public boolean hasCurrentMessageNumber() { return hasCurrentMessageNumber; }
    public int getCurrentMessageNumber() { return currentMessageNumber_; }
    
    // optional uint32 totalMessageNumber = 7;
    public static final int TOTALMESSAGENUMBER_FIELD_NUMBER = 7;
    private boolean hasTotalMessageNumber;
    private int totalMessageNumber_ = 0;
    public boolean hasTotalMessageNumber() { return hasTotalMessageNumber; }
    public int getTotalMessageNumber() { return totalMessageNumber_; }
    
    // optional .de.uniluebeck.itm.ubermep.mep.protocol.RPCMessage rpcMessage = 8;
    public static final int RPCMESSAGE_FIELD_NUMBER = 8;
    private boolean hasRpcMessage;
    private de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage rpcMessage_;
    public boolean hasRpcMessage() { return hasRpcMessage; }
    public de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage getRpcMessage() { return rpcMessage_; }
    
    private void initFields() {
      messageType_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType.UNICAST;
      rpcMessage_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasReliable) return false;
      if (!hasMessageType) return false;
      if (!hasPayload) return false;
      if (hasRpcMessage()) {
        if (!getRpcMessage().isInitialized()) return false;
      }
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasReliable()) {
        output.writeBool(1, getReliable());
      }
      if (hasMessageType()) {
        output.writeEnum(2, getMessageType().getNumber());
      }
      if (hasPayload()) {
        output.writeBytes(3, getPayload());
      }
      if (hasRequestID()) {
        output.writeUInt32(4, getRequestID());
      }
      if (hasExceptionOccurred()) {
        output.writeBool(5, getExceptionOccurred());
      }
      if (hasCurrentMessageNumber()) {
        output.writeUInt32(6, getCurrentMessageNumber());
      }
      if (hasTotalMessageNumber()) {
        output.writeUInt32(7, getTotalMessageNumber());
      }
      if (hasRpcMessage()) {
        output.writeMessage(8, getRpcMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasReliable()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getReliable());
      }
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getMessageType().getNumber());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPayload());
      }
      if (hasRequestID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getRequestID());
      }
      if (hasExceptionOccurred()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, getExceptionOccurred());
      }
      if (hasCurrentMessageNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getCurrentMessageNumber());
      }
      if (hasTotalMessageNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, getTotalMessageNumber());
      }
      if (hasRpcMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getRpcMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket result;
      
      // Construct using de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket();
        return builder;
      }
      
      protected de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.getDescriptor();
      }
      
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket getDefaultInstanceForType() {
        return de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket) {
          return mergeFrom((de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket other) {
        if (other == de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.getDefaultInstance()) return this;
        if (other.hasReliable()) {
          setReliable(other.getReliable());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasRequestID()) {
          setRequestID(other.getRequestID());
        }
        if (other.hasExceptionOccurred()) {
          setExceptionOccurred(other.getExceptionOccurred());
        }
        if (other.hasCurrentMessageNumber()) {
          setCurrentMessageNumber(other.getCurrentMessageNumber());
        }
        if (other.hasTotalMessageNumber()) {
          setTotalMessageNumber(other.getTotalMessageNumber());
        }
        if (other.hasRpcMessage()) {
          mergeRpcMessage(other.getRpcMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setReliable(input.readBool());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType value = de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setMessageType(value);
              }
              break;
            }
            case 26: {
              setPayload(input.readBytes());
              break;
            }
            case 32: {
              setRequestID(input.readUInt32());
              break;
            }
            case 40: {
              setExceptionOccurred(input.readBool());
              break;
            }
            case 48: {
              setCurrentMessageNumber(input.readUInt32());
              break;
            }
            case 56: {
              setTotalMessageNumber(input.readUInt32());
              break;
            }
            case 66: {
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.Builder subBuilder = de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.newBuilder();
              if (hasRpcMessage()) {
                subBuilder.mergeFrom(getRpcMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRpcMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required bool reliable = 1;
      public boolean hasReliable() {
        return result.hasReliable();
      }
      public boolean getReliable() {
        return result.getReliable();
      }
      public Builder setReliable(boolean value) {
        result.hasReliable = true;
        result.reliable_ = value;
        return this;
      }
      public Builder clearReliable() {
        result.hasReliable = false;
        result.reliable_ = false;
        return this;
      }
      
      // required .de.uniluebeck.itm.ubermep.mep.protocol.MessageType messageType = 2;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.MessageType.UNICAST;
        return this;
      }
      
      // required bytes payload = 3;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // optional uint32 requestID = 4;
      public boolean hasRequestID() {
        return result.hasRequestID();
      }
      public int getRequestID() {
        return result.getRequestID();
      }
      public Builder setRequestID(int value) {
        result.hasRequestID = true;
        result.requestID_ = value;
        return this;
      }
      public Builder clearRequestID() {
        result.hasRequestID = false;
        result.requestID_ = 0;
        return this;
      }
      
      // optional bool exceptionOccurred = 5;
      public boolean hasExceptionOccurred() {
        return result.hasExceptionOccurred();
      }
      public boolean getExceptionOccurred() {
        return result.getExceptionOccurred();
      }
      public Builder setExceptionOccurred(boolean value) {
        result.hasExceptionOccurred = true;
        result.exceptionOccurred_ = value;
        return this;
      }
      public Builder clearExceptionOccurred() {
        result.hasExceptionOccurred = false;
        result.exceptionOccurred_ = false;
        return this;
      }
      
      // optional uint32 currentMessageNumber = 6;
      public boolean hasCurrentMessageNumber() {
        return result.hasCurrentMessageNumber();
      }
      public int getCurrentMessageNumber() {
        return result.getCurrentMessageNumber();
      }
      public Builder setCurrentMessageNumber(int value) {
        result.hasCurrentMessageNumber = true;
        result.currentMessageNumber_ = value;
        return this;
      }
      public Builder clearCurrentMessageNumber() {
        result.hasCurrentMessageNumber = false;
        result.currentMessageNumber_ = 0;
        return this;
      }
      
      // optional uint32 totalMessageNumber = 7;
      public boolean hasTotalMessageNumber() {
        return result.hasTotalMessageNumber();
      }
      public int getTotalMessageNumber() {
        return result.getTotalMessageNumber();
      }
      public Builder setTotalMessageNumber(int value) {
        result.hasTotalMessageNumber = true;
        result.totalMessageNumber_ = value;
        return this;
      }
      public Builder clearTotalMessageNumber() {
        result.hasTotalMessageNumber = false;
        result.totalMessageNumber_ = 0;
        return this;
      }
      
      // optional .de.uniluebeck.itm.ubermep.mep.protocol.RPCMessage rpcMessage = 8;
      public boolean hasRpcMessage() {
        return result.hasRpcMessage();
      }
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage getRpcMessage() {
        return result.getRpcMessage();
      }
      public Builder setRpcMessage(de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRpcMessage = true;
        result.rpcMessage_ = value;
        return this;
      }
      public Builder setRpcMessage(de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.Builder builderForValue) {
        result.hasRpcMessage = true;
        result.rpcMessage_ = builderForValue.build();
        return this;
      }
      public Builder mergeRpcMessage(de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage value) {
        if (result.hasRpcMessage() &&
            result.rpcMessage_ != de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDefaultInstance()) {
          result.rpcMessage_ =
            de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.newBuilder(result.rpcMessage_).mergeFrom(value).buildPartial();
        } else {
          result.rpcMessage_ = value;
        }
        result.hasRpcMessage = true;
        return this;
      }
      public Builder clearRpcMessage() {
        result.hasRpcMessage = false;
        result.rpcMessage_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.ubermep.mep.protocol.MEPPacket)
    }
    
    static {
      defaultInstance = new MEPPacket(true);
      de.uniluebeck.itm.ubermep.mep.protocol.MEP.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.ubermep.mep.protocol.MEPPacket)
  }
  
  public static final class RPCMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use RPCMessage.newBuilder() to construct.
    private RPCMessage() {
      initFields();
    }
    private RPCMessage(boolean noInit) {}
    
    private static final RPCMessage defaultInstance;
    public static RPCMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public RPCMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.ubermep.mep.protocol.MEP.internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_fieldAccessorTable;
    }
    
    // required string serviceName = 1;
    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private boolean hasServiceName;
    private java.lang.String serviceName_ = "";
    public boolean hasServiceName() { return hasServiceName; }
    public java.lang.String getServiceName() { return serviceName_; }
    
    // required string methodName = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private boolean hasMethodName;
    private java.lang.String methodName_ = "";
    public boolean hasMethodName() { return hasMethodName; }
    public java.lang.String getMethodName() { return methodName_; }
    
    // required .de.uniluebeck.itm.ubermep.mep.protocol.ServiceType serviceType = 3;
    public static final int SERVICETYPE_FIELD_NUMBER = 3;
    private boolean hasServiceType;
    private de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType serviceType_;
    public boolean hasServiceType() { return hasServiceType; }
    public de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType getServiceType() { return serviceType_; }
    
    private void initFields() {
      serviceType_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType.SERVICE;
    }
    public final boolean isInitialized() {
      if (!hasServiceName) return false;
      if (!hasMethodName) return false;
      if (!hasServiceType) return false;
      return true;
    }

	  @Override
	  protected Message.Builder newBuilderForType(BuilderParent parent) {
		  return new Builder(parent);
	  }

	  public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasServiceName()) {
        output.writeString(1, getServiceName());
      }
      if (hasMethodName()) {
        output.writeString(2, getMethodName());
      }
      if (hasServiceType()) {
        output.writeEnum(3, getServiceType().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasServiceName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getServiceName());
      }
      if (hasMethodName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMethodName());
      }
      if (hasServiceType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, getServiceType().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage result;
      
      // Construct using de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.newBuilder()
      private Builder() {}

		public Builder(BuilderParent parent) {
			super(parent);
		}

		private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage();
        return builder;
      }
      
      protected de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage();
        return this;
      }

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_fieldAccessorTable;
		}

		public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDescriptor();
      }
      
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage getDefaultInstanceForType() {
        return de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage) {
          return mergeFrom((de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage other) {
        if (other == de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          setServiceName(other.getServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasServiceType()) {
          setServiceType(other.getServiceType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setServiceName(input.readString());
              break;
            }
            case 18: {
              setMethodName(input.readString());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType value = de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                setServiceType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // required string serviceName = 1;
      public boolean hasServiceName() {
        return result.hasServiceName();
      }
      public java.lang.String getServiceName() {
        return result.getServiceName();
      }
      public Builder setServiceName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceName = true;
        result.serviceName_ = value;
        return this;
      }
      public Builder clearServiceName() {
        result.hasServiceName = false;
        result.serviceName_ = getDefaultInstance().getServiceName();
        return this;
      }
      
      // required string methodName = 2;
      public boolean hasMethodName() {
        return result.hasMethodName();
      }
      public java.lang.String getMethodName() {
        return result.getMethodName();
      }
      public Builder setMethodName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMethodName = true;
        result.methodName_ = value;
        return this;
      }
      public Builder clearMethodName() {
        result.hasMethodName = false;
        result.methodName_ = getDefaultInstance().getMethodName();
        return this;
      }
      
      // required .de.uniluebeck.itm.ubermep.mep.protocol.ServiceType serviceType = 3;
      public boolean hasServiceType() {
        return result.hasServiceType();
      }
      public de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType getServiceType() {
        return result.getServiceType();
      }
      public Builder setServiceType(de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasServiceType = true;
        result.serviceType_ = value;
        return this;
      }
      public Builder clearServiceType() {
        result.hasServiceType = false;
        result.serviceType_ = de.uniluebeck.itm.ubermep.mep.protocol.MEP.ServiceType.SERVICE;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.ubermep.mep.protocol.RPCMessage)
    }
    
    static {
      defaultInstance = new RPCMessage(true);
      de.uniluebeck.itm.ubermep.mep.protocol.MEP.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.ubermep.mep.protocol.RPCMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/resources/mep.proto\022&de.unilu" +
      "ebeck.itm.ubermep.mep.protocol\"\250\002\n\tMEPPa" +
      "cket\022\020\n\010reliable\030\001 \002(\010\022H\n\013messageType\030\002 " +
      "\002(\01623.de.uniluebeck.itm.ubermep.mep.prot" +
      "ocol.MessageType\022\017\n\007payload\030\003 \002(\014\022\021\n\treq" +
      "uestID\030\004 \001(\r\022\031\n\021exceptionOccurred\030\005 \001(\010\022" +
      "\034\n\024currentMessageNumber\030\006 \001(\r\022\032\n\022totalMe" +
      "ssageNumber\030\007 \001(\r\022F\n\nrpcMessage\030\010 \001(\01322." +
      "de.uniluebeck.itm.ubermep.mep.protocol.R" +
      "PCMessage\"\177\n\nRPCMessage\022\023\n\013serviceName\030\001",
      " \002(\t\022\022\n\nmethodName\030\002 \002(\t\022H\n\013serviceType\030" +
      "\003 \002(\01623.de.uniluebeck.itm.ubermep.mep.pr" +
      "otocol.ServiceType*\256\001\n\013MessageType\022\013\n\007UN" +
      "ICAST\020\001\022\r\n\tMULTICAST\020\002\022\033\n\027SINGLE_RESPONS" +
      "E_REQUEST\020\003\022\032\n\026MULTI_RESPONSE_REQUEST\020\004\022" +
      "\023\n\017SINGLE_RESPONSE\020\005\022\022\n\016MULTI_RESPONSE\020\006" +
      "\022\017\n\013RPC_REQUEST\020\007\022\020\n\014RPC_RESPONSE\020\010*0\n\013S" +
      "erviceType\022\013\n\007SERVICE\020\001\022\024\n\020BLOCKING_SERV" +
      "ICE\020\002B\007B\003MEPH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_ubermep_mep_protocol_MEPPacket_descriptor,
              new java.lang.String[] { "Reliable", "MessageType", "Payload", "RequestID", "ExceptionOccurred", "CurrentMessageNumber", "TotalMessageNumber", "RpcMessage", },
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.class,
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.MEPPacket.Builder.class);
          internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_ubermep_mep_protocol_RPCMessage_descriptor,
              new java.lang.String[] { "ServiceName", "MethodName", "ServiceType", },
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.class,
              de.uniluebeck.itm.ubermep.mep.protocol.MEP.RPCMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
